### ISSUE TITLE
Allow to set an audio codec per channel

### ISSUE THREAD

**Issue by felipecrs** [gtxaspec/prudynt-t#62]
OPUS is great and is the best audio codec hands down.

But sometimes we need other codecs, like some legacy HLS (browser) players can only play AAC audio.

go2rtc can be used for that:

```yaml
streams:
  my_cam:
    - rtsp://thingino:thingino@192.168.1.31/ch1
    - ffmpeg:my_cam#audio=aac
```

But this will invoke `ffmpeg` on the receiving end, which consumes CPU resources and (probably) adds some latency.

It would be great if we could have different audio codecs per channel, so that I could do something like this in go2rtc:

```yaml
streams:
  my_cam:
    # ch1 would be set to send OPUS
    - rtsp://thingino:thingino@192.168.1.31/ch1
    - rtsp://127.0.0.1:8554/my_cam_hd?audio=aac
  my_cam_hd:
    # ch0 would be set to send AAC
    - rtsp://thingino:thingino@192.168.1.31/ch0
    - rtsp://127.0.0.1:8554/my_cam?audio=opus
```

Which would not require any transcoding. :)
